name: Build rootfs for oracular
on: 
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        sudo apt update
        sudo apt install curl jq mmdebstrap qemu-user-static binfmt-support multistrap
        sudo chmod a+x *.sh
    - name: Build
      run: ./mmbootstrap-oracular.sh
    - name: Pack rootfs
      run: ./pack-rootfs-oracular.sh
    - name: Upload rootfs
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-oracular-arm64-rootfs.tar.xz
        path: ubuntu-oracular-arm64-rootfs.tar.xz
