name: Build rootfs

on: push

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        sudo apt update
        sudo apt install curl debian-archive-keyring jq mmdebstrap qemu-user-static binfmt-support multistrap
        sudo chmod a+x *.sh
    - name: Build
      run: ./mmbootstrap.sh
    - name: Pack rootfs
      run: ./pack-rootfs.sh
    - name: Upload rootfs
      uses: actions/upload-artifact@v4
      with:
        name: debian-sid-arm64-rootfs.tar.xz
        path: debian-sid-arm64-rootfs.tar.xz
#    - name: Upload rootfs to Release
#      uses: softprops/action-gh-release@v2
#      with:
#          files: debian-sid-arm64-rootfs.tar.xz
