name: Build rootfs for plucky
on: 
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        sudo apt update
        sudo apt install curl jq mmdebstrap qemu-user-static binfmt-support multistrap
        sudo chmod a+x *.sh
    - name: Build
      run: ./mmbootstrap-plucky.sh
    - name: Pack rootfs
      run: ./pack-rootfs-plucky.sh
    - name: Upload rootfs
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-plucky-arm64-rootfs.tar.xz
        path: ubuntu-plucky-arm64-rootfs.tar.xz
