name: Build rootfs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        sudo apt update
        sudo apt install curl debian-archive-keyring jq mmdebstrap qemu-user-static binfmt-support multistrap
        sudo chmod a+x *.sh
    - name: Build
      run: ./mmbootstrap.sh
    - name: Pack rootfs
      run: ./pack-rootfs.sh
    - name: Upload rootfs to Release
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path:  debian-sid-arm64-rootfs.tar.xz
          asset_name:  debian-sid-arm64-rootfs.tar.xz
          asset_content_type: application/zip
